### ISSUE TITLE
Unable to sign commits with a PGP key: `No pinentry`

### ISSUE THREAD

**Issue by YeldhamDev** [flathub/com.github.git_cola.git-cola#41]
When attempting to sign a commit using a PGP key, this error will occur:
```
error: gpg failed to sign the data:
[GNUPG:] KEY_CONSIDERED ****************************
[GNUPG:] BEGIN_SIGNING H8
gpg: signing failed: No pinentry
[GNUPG:] FAILURE sign ********
gpg: signing failed: No pinentry

fatal: failed to write commit object
```

I assume that's because the program can't access the pinentry binary due to the sandbox. Is there any workaround?

**Comment by Mailaender** [comment]
You could try adding `--socket=gpg-agent` https://docs.flatpak.org/de/latest/sandbox-permissions-reference.html
